# Generated by Django 4.0.3 on 2022-12-05 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qa', '0006_qdownvote_historicalqdownvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions_Flag_Q', models.CharField(choices=[('SPAM', 'Spam'), ('RUDE_OR_ABUSIVE', 'Rude or Abusive'), ('NOT_AN_ANSWER', 'Not an Answer'), ('IN_NEED_OF_MODERATOR_INTERVATION', 'In Need of Moderator Intervation'), ('VERY_LOW_QUALITY', 'Very Low Quality'), ('NEEDS_IMPROVEMENT', 'Needs Improvement'), ('DUPLICATE', 'Duplicate'), ('OPINION_BASED', 'Opinion Based'), ('NEED_MORE_FOCUS', 'Need More Focus# = QUESTION'), ('NEED_ADDITIONAL_DETAILS', 'Needs Additional Details'), ('A_COMMUNITY_SPECIFIC_REASON', 'A Community specific reason'), ('ABOUT_GENERAL_COMPUTING_HAR', 'About General'), ('ABOUT_PROFESSIONAL', 'About Professional'), ('SEEKING_RECCOMENDATIONS', 'Seeking Reccomendations'), ('NEED_DEBUGGING', 'Need Debugging Details'), ('NOT_REPRODUCIBLE', 'Not Reproducible'), ('BLANTANLTY_OR_CLARITY', 'Blantanlity or Clarity')], max_length=300)),
                ('how_many_votes_on_spamANDRude', models.IntegerField(default=0)),
                ('how_many_votes_on_notAnAnswer', models.IntegerField(default=0)),
                ('how_many_votes_on_others', models.IntegerField(default=0)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('ended', models.BooleanField(default=False)),
                ('answer_forFlag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.answer')),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_forFlag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.question')),
            ],
        ),
    ]
