# Generated by Django 4.0.3 on 2022-10-23 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_remove_profile_full_name_remove_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='enrollmentid',
            field=models.CharField(default='BT19CSE000', max_length=10, validators=[django.core.validators.RegexValidator('^BT\\d{2}\\w{3,4}\\d{3}$')]),
        ),
    ]
