# Generated by Django 4.0.3 on 2022-10-23 17:21

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_profile_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(default='1111111111', max_length=128, region=None),
        ),
    ]
