# Generated by Django 4.0.3 on 2022-10-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_alter_profile_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='create_tags',
            field=models.BooleanField(default=False),
        ),
    ]
