# Generated by Django 4.0.3 on 2023-04-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_qdownvote_historicalqdownvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(default='', max_length=100),
        ),
    ]
