# Generated by Django 4.1 on 2023-05-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0007_remove_question_tags_question_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalqdownvote",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical q downvote",
                "verbose_name_plural": "historical q downvotes",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalqupvote",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical q upvote",
                "verbose_name_plural": "historical q upvotes",
            },
        ),
        migrations.AlterField(
            model_name="historicalqdownvote",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalqupvote",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
